
# cargo-vet config file

[cargo-vet]
version = "0.6"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.geocode-csv]
audit-as-crates-io = true

[policy.libpostal-rust]
audit-as-crates-io = true

[policy.libpostal-sys]
audit-as-crates-io = true

[policy.metrics-exporter-newrelic]
audit-as-crates-io = true

[policy.opinionated_metrics]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "0.7.20"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.async-stream]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.async-stream-impl]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.68"
criteria = "safe-to-deploy"

[[exemptions.autotools]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.6.18"
criteria = "safe-to-deploy"

[[exemptions.axum-core]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.67"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.bb8]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.bb8-redis]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.bigtable_rs]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "2.0.0-rc.3"
criteria = "safe-to-deploy"

[[exemptions.bincode_derive]]
version = "2.0.0-rc.3"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.79"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.24"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.cli_test_dir]]
version = "0.1.7"
criteria = "safe-to-run"

[[exemptions.colorchoice]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.combine]]
version = "4.6.6"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.14"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.15"
criteria = "safe-to-deploy"

[[exemptions.csv]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.csv-core]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.ctor]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.cxx]]
version = "1.0.94"
criteria = "safe-to-deploy"

[[exemptions.cxx-build]]
version = "1.0.94"
criteria = "safe-to-deploy"

[[exemptions.cxxbridge-macro]]
version = "1.0.94"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.1"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.1"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.1"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.dirs-next]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys-next]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.endian-type]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.erased-serde]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.errno-dragonfly]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.fs_extra]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.gcp_auth]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.geocode-csv]]
version = "1.3.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.ghost]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.27.2"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.18"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.26"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.23.2"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.56"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.3"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.inventory]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.7.2"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.jemalloc-sys]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.jemallocator]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.62"
criteria = "safe-to-deploy"

[[exemptions.leaky-bucket]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.144"
criteria = "safe-to-deploy"

[[exemptions.libpostal-rust]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.libpostal-sys]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.link-cplusplus]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.mach]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.matchit]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.metrics]]
version = "0.20.1"
criteria = "safe-to-deploy"

[[exemptions.metrics-exporter-newrelic]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.metrics-exporter-prometheus]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.metrics-macros]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.metrics-util]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.mopa]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.multimap]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.nibble_vec]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.30.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.17.1"
criteria = "safe-to-deploy"

[[exemptions.opinionated_metrics]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "2.10.0"
criteria = "safe-to-deploy"

[[exemptions.overload]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.7"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "0.3.20"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.prettyplease]]
version = "0.1.25"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.prost-build]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.prost-types]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.prost-wkt]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.prost-wkt-build]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.prost-wkt-types]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.quanta]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.radix_trie]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.raw-cpuid]]
version = "10.7.0"
criteria = "safe-to-deploy"

[[exemptions.redis]]
version = "0.22.3"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.29"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.reqwest]]
version = "0.11.17"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.37.19"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.20.8"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.13"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.scratch]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.8.2"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.163"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.163"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.96"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.serde_with]]
version = "2.3.3"
criteria = "safe-to-deploy"

[[exemptions.serde_with_macros]]
version = "2.3.3"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.sketches-ddsketch]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.strum_macros]]
version = "0.24.3"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.15"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.5.0"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.terminal_size]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.40"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.40"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.28.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-io-timeout]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.23.4"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.14"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.tonic]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.tonic-build]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.37"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.tracing-futures]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.typetag]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.typetag-impl]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.unicode-bidi]]
version = "0.3.13"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.virtue]]
version = "0.0.13"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.10.2+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.85"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.85"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.35"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.85"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.85"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.85"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.62"
criteria = "safe-to-deploy"

[[exemptions.webpki]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.22.6"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.winreg]]
version = "0.10.1"
criteria = "safe-to-deploy"
